### ISSUE TITLE
Missing Components?

### ISSUE THREAD

**Issue by Pxrallel** [iandiv/Win11Tweaker#1]
when trying view the forms in the source it says the the namespace 'CustomComponent' could not be found

**Comment by iandiv** [comment]
> when trying view the forms in the source it says the the namespace 'CustomComponent' could not be found

sorry i forgot to include the custom component, I will upload it later

**Comment by iandiv** [comment]
Custom Components Uploaded
https://github.com/iandiv/Win11Tweaker/tree/master/Win11Tweaker/Custom%20Components

just import the dll in your Visual Studio Toolbox

**Comment by iandiv** [comment]
Custom Components Uploaded
https://github.com/iandiv/Win11Tweaker/tree/master/Win11Tweaker/Custom%20Components

just import the dll in your Visual Studio Toolbox
